### ISSUE TITLE
Improve image CSS reset

### ISSUE THREAD

**Issue by hasanhaja** [hasanhaja/site#25]
This feels like a better style reset: https://www.youtube.com/watch?v=345V2MU3E_w

I also think I can automate a lot of it using my own image optimization pipeline: https://github.com/hasanhaja/pixels/

```css
img {
  max-width: 100%;
  height: auto;
  vertical-align: middle;
  font-style: italic;
  background-repeat: no-repeat;
  background-size: cover;
  shape-margin: 0.75rem; /* or any other default value */
}
```

## Todo
- [ ] Add default image size
- [ ] Extract this to a web component/webc component
